export const ExpertRegForm = [
    {
        name: 'first_name',
        label: 'First Name',
        type: 'text',
        value: '',
        placeholder: 'Enter First Name',
      },
      {
        name: 'last_name',
        label: 'Last Name',
        type: 'text',
        value: '',
        placeholder: 'Enter Last Name',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        value: '',
        placeholder: 'Enter Email Address',
      },
      {
        name: 'phone_number',
        label: 'Phone Number',
        type: 'text',
        value: '',
        placeholder: 'Enter Phone Number',
      },
      {
        name: 'country_id',
        label: 'Country of Origin',
        type: 'select',
        value: '',
        placeholder: 'Select Country',
      },
      {
        name: 'state',
        label: 'State',
        type: 'select',
        value: '',
        placeholder: 'Select State',
      },
      {
        name: 'city',
        label: 'City / Town',
        type: 'select',
        value: '',
        placeholder: 'Select City',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        value: '',
        placeholder: 'Enter Password',
      },
      {
        name: 'c_password',
        label: 'Confirm Password',
        type: 'password',
        value: '',
        placeholder: 'Enter Confirm Password',
      },
      {
        name: 'account_type',
        label: '',
        type: 'hidden',
        value: 'expert',
        placeholder: '',
      },
];